# Generated by Django 4.1.6 on 2023-03-02 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_room_capacity_room_isbooked_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='isBooked',
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBooked', models.BooleanField()),
                ('bookingDate', models.DurationField()),
                ('roomId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.room')),
            ],
        ),
    ]
