# Generated by Django 4.1.6 on 2023-03-08 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Номер комнаты')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('capacity', models.IntegerField(verbose_name='Количество мест')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание комнаты')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='BookedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('bookedDateFrom', models.DateField(default=datetime.datetime(2023, 3, 8, 16, 48, 25, 322429, tzinfo=datetime.timezone.utc), verbose_name='с:')),
                ('bookedDateTo', models.DateField(default=datetime.datetime(2023, 3, 8, 16, 48, 25, 322429, tzinfo=datetime.timezone.utc), verbose_name='по:')),
                ('bookedRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
            options={
                'verbose_name': 'Забронированная комната',
                'verbose_name_plural': 'Забронированные комнаты',
            },
        ),
    ]
