# Generated by Django 4.1.6 on 2023-03-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
