# Generated by Django 4.1.6 on 2023-03-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_room_isbooked_bookingroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookedDate', models.DurationField()),
                ('bookedRoomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.room')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
        ),
        migrations.DeleteModel(
            name='BookingRoom',
        ),
    ]
